FROM ubuntu:latest
RUN apt-get update
RUN apt install -y systemd
RUN apt install -y openjdk-11-jdk
RUN apt install -y vim
RUN apt install -y postgresql postgresql-contrib
RUN systemctl enable postgresql.service

USER root
RUN mkdir /usr/lib/postgresql/12/pgsql
RUN chown postgres /usr/lib/postgresql/12/pgsql
RUN su postgres
RUN postgres$ initdb -D /usr/lib/postgresql/12/pgsql/data 

USER postgres

#RUN /etc/init.d/postgresql start &&\
#    psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
#    createdb -O docker docker
   
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/12/main/pg_hba.conf    
RUN echo "listen_addresses='*'" >> /etc/postgresql/12/main/postgresql.conf
# Expose the PostgreSQL port
EXPOSE 5432
 
ENV PGDATA=/data

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
 
# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/12/bin/postgres", "-D", "/var/lib/postgresql/12/main", "-c", "config_file=/etc/postgresql/12/main/postgresql.conf"]